//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindGhC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextFilesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextFilesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindGhC.TextFilesResources", typeof(TextFilesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // -*- C++ -*-
        ///// File generated by PyFoam - sorry for the ugliness
        ///
        ///FoamFile
        ///{
        /// version 2.0;
        /// format ascii; 	
        /// class dictionary; 	
        /// object decomposeParDict; 	
        ///}
        ///
        ///numberOfSubdomains 6;
        ///
        ///method scotch; 	
        ///
        ///.
        /// </summary>
        internal static string decomposeParDict {
            get {
                return ResourceManager.GetString("decomposeParDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #!/bin/sh
        ///
        ///#PBS -j oe
        ///#PBS -N Solver1
        ///#PBS -l nodes=3:ppn=6
        ///#PBS -l walltime=1000000:00:00
        ///###output files
        ///###PBS -e err.log
        ///###PBS -o out.log
        ///###Mail to user
        ///#PBS -m ae
        ///#PBS -M andersson@str-ucture.com
        ///
        ///cd $PBS_O_WORKDIR
        ///
        ///LOGFILE=&quot;${PBS_O_WORKDIR}/out.log&quot;
        ///ERRFILE=&quot;${PBS_O_WORKDIR}/err.log&quot;
        ///NODEFILE=&quot;${PBS_O_WORKDIR}/nodes.log&quot;
        ///
        ///cat $PBS_NODEFILE &gt;$NODEFILE
        ///
        ///export NUM_CPUS=18
        ///export NUM_NODES=3
        ///
        ///#rm -r processor*
        ///
        ///# reconfigure decomposition method
        ///
        ///sed -i &quot;s/method ptscotch/method scotch/g&quot; system/decomp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string foam {
            get {
                return ResourceManager.GetString("foam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FoamFile
        ///{
        ///    version 2.0;
        ///    format ascii;
        ///    class dictionary;
        ///    object fvSchemes;
        ///}
        ///
        ///// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
        ///    ddtSchemes
        ///    {
        ///        default        	backward;
        ///    }
        ///    gradSchemes
        ///    {
        /////      default         cellLimited Gauss linear 1.0;
        ///       default         cellLimited leastSquares 1.0;
        ///       grad(p)         cellLimited Gauss linear 1.0;
        /////        grad(U)         Gauss linear;
        ///    }
        ///    divSchemes
        ///    {
        ///        default         Gauss [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fvSchemes {
            get {
                return ResourceManager.GetString("fvSchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FoamFile
        ///{
        ///    version 2.0;
        ///    format ascii;
        ///    class dictionary;
        ///    object fvSolution;
        ///}
        ///
        ///// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
        ///    SIMPLE
        ///    {
        ///        nNonOrthogonalCorrectors 10;
        ///        pressureImplicitPorousity false;
        ///        pRefCell        0;
        ///        pRefValue       0;
        ///    }
        ///    PISO
        ///    {
        ///        nNonOrthogonalCorrectors 1;
        ///        nCorrectors     4;
        ///        pRefCell        0;
        ///        pRefValue       0;
        ///    }
        ///    PIMPLE
        ///    {
        ///        nNonOrthogonalCorrec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fvSolution {
            get {
                return ResourceManager.GetString("fvSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.1.0                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LESProperties {
            get {
                return ResourceManager.GetString("LESProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #!/bin/sh
        ///
        ///#PBS -j oe
        ///#PBS -N Mesh1
        ///#PBS -l nodes=1:ppn=6
        ///#PBS -l walltime=1000000:00:00
        ///###output files
        ///###PBS -e err.log
        ///###PBS -o out.log
        ///###Mail to user
        ///#PBS -m ae
        ///#PBS -M andersson@str-ucture.com
        ///
        ///cd $PBS_O_WORKDIR
        ///
        ///LOGFILE=&quot;${PBS_O_WORKDIR}/out.log&quot;
        ///ERRFILE=&quot;${PBS_O_WORKDIR}/err.log&quot;
        ///NODEFILE=&quot;${PBS_O_WORKDIR}/nodes.log&quot;
        ///
        ///cat $PBS_NODEFILE &gt;$NODEFILE
        ///
        ///export NUM_CPUS=6
        ///export NUM_NODES=1
        ///
        ///#rm -r processor*
        ///
        ///
        ///#
        ///# deompose based on pimpleDyMFsiFoam
        ///#
        ///
        ///sed -i &quot;s/pimpleDyMFoam/pimpleDyMFsiFoam/g&quot; system/c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mesh {
            get {
                return ResourceManager.GetString("mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.2.0                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RASProperties {
            get {
                return ResourceManager.GetString("RASProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  1.5                                   |
        ///|   \\  /    A nd           | Web:      http://www.OpenFOAM.org               |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string transportProperties {
            get {
                return ResourceManager.GetString("transportProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.2.0                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string turbulenceProperties {
            get {
                return ResourceManager.GetString("turbulenceProperties", resourceCulture);
            }
        }
    }
}
